#!/usr/bin/env python3

"""Generate the data rows for the verification counts table.

The rows are generated from the `kill-scores.txt` files in each subject program
directory of each treatment. Each `kill-scores.txt` ends with one Python-dict
line per function (e.g. `{'function': 'abAppend', ..., 'is_verified': True, ...}`)
and begins with a line naming the C file processed (`... Processing .../kilo.c`).
For each (treatment, subject), the number of verified functions is the number of
dicts with `is_verified == True`, and the total number of functions is the number
of dict lines.

Usage:
    % ./scripts/generate_verification_counts_table.py

"""

import ast
import re

from util import (
    all_treatments_have_same_subjects,
    get_directories,
)

from collections import defaultdict
from pathlib import Path
from dataclasses import dataclass

# Treatments in the same order as the columns of the verification counts table:
#   Baseline, Full, -Curated docs, -Tools, -Mutation testing, -Harness
TREATMENTS = [
    "pure-agentic-baseline",
    "full",
    "minus-docs",
    "minus-tools",
    "minus-mutation-testing",
    "minus-harness",
]

KILL_SCORES_FILE_NAME = "kill-scores.txt"

# Marker emitted for a (subject, treatment) cell that has no `kill-scores.txt`.
MISSING_CELL = "\\todo{}"


@dataclass(frozen=True)
class FileVerificationResult:
    treatment: str
    file_name: str
    num_functions: int
    num_verified: int


def main() -> None:
    file_to_treatment_results: dict[str, dict[str, FileVerificationResult]] = (
        defaultdict(dict)
    )
    for treatment, subject_program_dirs in treatments_to_subject_program_dirs().items():
        for subject_program_dir in subject_program_dirs:
            result = parse_file_verification_results(
                treatment, subject_program_dir / KILL_SCORES_FILE_NAME
            )
            if result is not None:
                file_to_treatment_results[result.file_name][treatment] = result
    print(f"% Do not edit; these rows are automatically generated by: experimental-data/scripts/generate_verification_counts_table.py")
    for row in get_table_rows(dict(file_to_treatment_results)):
        print(row)


def treatments_to_subject_program_dirs() -> dict[str, list[Path]]:
    """Return a dictionary from treatment to list of subject programs directories.

    Returns:
        dict[str, list[Path]]: A dictionary from treatment to list of subject program directories.
    """
    treatments_to_subject_dirs = {
        treatment: get_directories(f"{treatment}") for treatment in TREATMENTS
    }
    if not all_treatments_have_same_subjects(treatments_to_subject_dirs):
        raise ValueError(f"Inconsistent subject programs across treatments")
    return treatments_to_subject_dirs


def parse_file_verification_results(
    treatment: str,
    path_to_kill_scores_file: Path,
) -> FileVerificationResult | None:
    """Return the verification result parsed from a `kill-scores.txt` file.

    Args:
        treatment (str): The treatment.
        path_to_kill_scores_file (Path): The path to the kill scores file.

    Returns:
        FileVerificationResult | None: The verification result parsed from the
            `kill-scores.txt` file, or None if the file does not exist.
    """
    if not path_to_kill_scores_file.is_file():
        return None
    lines = path_to_kill_scores_file.read_text(encoding="utf-8").splitlines()
    file_name = get_processed_file_name(lines)
    num_functions = 0
    num_verified = 0
    for line in lines:
        function_record = parse_function_record(line)
        if function_record is None:
            continue
        num_functions += 1
        if function_record.get("is_verified"):
            num_verified += 1
    if file_name is None:
        raise ValueError(
            f"Could not find a 'Processing' line in {path_to_kill_scores_file}"
        )
    return FileVerificationResult(treatment, file_name, num_functions, num_verified)


def get_processed_file_name(lines: list[str]) -> str | None:
    """Return the C file name from the `Processing ...` log line in a kill-scores file.

    For example, for a line containing:

        Processing experimental-data/full/Syzygy_Zopfli/c_code/zopfli.c

    returns `zopfli.c`.

    Args:
        lines (list[str]): The lines of a `kill-scores.txt` file.

    Returns:
        str | None: The processed C file's basename, or None if not found.
    """
    for line in lines:
        if match := re.search(r"Processing\s+(\S+\.\w+)", line):
            return Path(match.group(1)).name


def parse_function_record(line: str) -> dict | None:
    """Return the per-function record dict parsed from a `kill-scores.txt` line.

    Args:
        line (str): A line from a `kill-scores.txt` file.

    Returns:
        dict | None: The parsed dict (e.g. `{'function': ..., 'is_verified': ...}`),
            or None if the line is not a function record.
    """
    stripped = line.strip()
    if not (stripped.startswith("{") and "'function'" in stripped):
        return None
    try:
        record = ast.literal_eval(stripped)
    except (ValueError, SyntaxError):
        return None
    return record if isinstance(record, dict) else None


def get_table_rows(
    file_to_treatment_results: dict[str, dict[str, FileVerificationResult]],
) -> list[str]:
    """Return all the (data) rows of the verification counts table.

    Args:
        file_to_treatment_results (dict[str, dict[str, FileVerificationResult]]): Map from
            file name to per-treatment verification results.

    Returns:
        list[str]: The data rows of the verification counts table.
    """
    total_functions = 0
    # Per-treatment running totals; None marks a treatment that is missing data
    # for at least one subject (its Total cell becomes \todo{}).
    total_verified_per_treatment: list[int | None] = [0] * len(TREATMENTS)
    lines = []
    for file_name in sorted(file_to_treatment_results):
        results_by_treatment = file_to_treatment_results[file_name]
        num_functions = next(
            result.num_functions for result in results_by_treatment.values()
        )
        num_verified_per_treatment = [
            results_by_treatment[treatment].num_verified
            if treatment in results_by_treatment
            else None
            for treatment in TREATMENTS
        ]
        total_functions += num_functions
        total_verified_per_treatment = [
            None if running is None or count is None else running + count
            for running, count in zip(
                total_verified_per_treatment, num_verified_per_treatment
            )
        ]
        lines.append(
            get_row(f"\\<{file_name}>", num_functions, num_verified_per_treatment)
        )
    lines.append("\\midrule")
    lines.append(
        get_row("\\textbf{Total}", total_functions, total_verified_per_treatment)
    )
    return lines


def get_row(
    file_name: str,
    num_functions_in_file: int,
    num_verifying_functions_per_treatment: list[int | None],
) -> str:
    """Return one row of the verification counts table.

    Each treatment cell reports the percentage of functions verified; the leading
    column reports the total number of functions in the file.

    Args:
        file_name (str): The file name.
        num_functions_in_file (int): The number of functions in the file.
        num_verifying_functions_per_treatment (list[int | None]): The number of functions
            verified per treatment, or None for a treatment with missing data.

    Returns:
        str: One row of the verification counts table.
    """
    # Bold every treatment that ties for the highest (displayed) percentage.
    percentages = [
        None if count is None else round(count / num_functions_in_file * 100)
        for count in num_verifying_functions_per_treatment
    ]
    present_percentages = [
        percentage for percentage in percentages if percentage is not None
    ]
    max_percentage = max(present_percentages) if present_percentages else None
    cells = [str(num_functions_in_file)]
    for percentage in percentages:
        if percentage is None:
            cells.append(MISSING_CELL)
            continue
        cell = f"{percentage}\\%"
        if percentage == max_percentage:
            cell = f"\\textbf{{{cell}}}"
        cells.append(cell)
    return f"{file_name} & {' & '.join(cells)} \\\\"


if __name__ == "__main__":
    main()
