#!/usr/bin/env python3

"""Generate the data rows for the mutation kill-scores table.

The rows are generated from the `kill-scores.txt` files in each subject program
directory of each treatment. Each `kill-scores.txt` ends with one Python-dict
line per function (e.g.
`{'function': 'abAppend', ..., 'has_mutants': True, 'is_verified': True, 'num_mutants': 3, 'num_killed': 0}`)
and begins with a line naming the C file processed (`... Processing .../kilo.c`).

For each (treatment, subject) we aggregate, over the functions that have mutants,
the number of mutants and the number killed (only verified functions can kill
mutants). The kill score is killed / mutants. Per the table design, each cell
shows only the kill score (a fraction in [0, 1]) and the `Mutants` column shows
the Full treatment's total mutants for the subject.

Usage:
    % ./scripts/generate_mutation_kill_scores.py

"""

import ast

from util import (
    all_treatments_have_same_subjects,
    get_directories,
)

from collections import defaultdict
from pathlib import Path
from dataclasses import dataclass

# Treatments in the same order as the columns of the kill-scores table:
#   Baseline, Full, -Curated docs, -Tools, -Mutation testing, -Harness
TREATMENTS = [
    "pure-agentic-baseline",
    "full",
    "minus-docs",
    "minus-tools",
    "minus-mutation-testing",
    "minus-harness",
]

# The treatment whose total mutants populate the `Mutants` column.
MUTANTS_COLUMN_TREATMENT = "full"

MUTATION_SCORE_FILE_NAME = "kill-scores.txt"

# Marker emitted for a cell that has no data (missing file or no mutants).
MISSING_CELL = "\\todo{}"


@dataclass(frozen=True)
class MutationTestingResultForFunction:
    file_name: str
    function: str
    has_annotations: bool
    has_mutants: bool
    is_verified: bool
    num_mutants: int
    num_killed: int


@dataclass(frozen=True)
class SubjectKillScore:
    """Aggregated mutation-testing result for one (treatment, subject)."""

    num_mutants: int
    num_killed: int

    @property
    def kill_score(self) -> float | None:
        """Return killed / mutants, or None if there are no mutants."""
        if self.num_mutants == 0:
            return None
        return self.num_killed / self.num_mutants


def main() -> None:
    file_to_treatment_scores: dict[str, dict[str, SubjectKillScore]] = defaultdict(dict)
    for treatment, subject_program_dirs in treatments_to_subject_program_dirs().items():
        for subject_program_dir in subject_program_dirs:
            for file_name, score in aggregate_kill_scores(
                subject_program_dir / MUTATION_SCORE_FILE_NAME
            ).items():
                file_to_treatment_scores[file_name][treatment] = score
    print(f"% Do not edit; these rows are automatically generated by: experimental-data/scripts/generate_mutation_kill_scores.py")
    for row in get_table_rows(dict(file_to_treatment_scores)):
        print(row)


def treatments_to_subject_program_dirs() -> dict[str, list[Path]]:
    """Return a dictionary from treatment to list of subject programs directories.

    Returns:
        dict[str, list[Path]]: A dictionary from treatment to list of subject program directories.
    """
    treatments_to_subject_dirs = {
        treatment: get_directories(f"{treatment}") for treatment in TREATMENTS
    }
    if not all_treatments_have_same_subjects(treatments_to_subject_dirs):
        raise ValueError(f"Inconsistent subject programs across treatments")
    return treatments_to_subject_dirs


def aggregate_kill_scores(
    path_to_kill_scores_file: Path,
) -> dict[str, SubjectKillScore]:
    """Return the aggregated kill score per subject file in a `kill-scores.txt` file.

    Args:
        path_to_kill_scores_file (Path): The path to the kill score file.

    Returns:
        dict[str, SubjectKillScore]: Map from subject `.c` file name to its aggregated
            kill score. Empty if the file does not exist.
    """
    results = parse_mutation_testing_results(path_to_kill_scores_file)
    file_to_mutants: dict[str, int] = defaultdict(int)
    file_to_killed: dict[str, int] = defaultdict(int)
    for result in results:
        if not result.has_mutants:
            continue
        file_to_mutants[result.file_name] += result.num_mutants
        if result.is_verified:
            file_to_killed[result.file_name] += result.num_killed
    return {
        file_name: SubjectKillScore(num_mutants, file_to_killed[file_name])
        for file_name, num_mutants in file_to_mutants.items()
    }


def parse_mutation_testing_results(
    path_to_kill_scores_file: Path,
) -> list[MutationTestingResultForFunction]:
    """Return the mutation testing results parsed from a `kill-scores.txt` file.

    Args:
        path_to_kill_scores_file (Path): The path to the kill score file.

    Returns:
        list[MutationTestingResultForFunction]: The mutation testing results for a file.
    """
    mutation_testing_results = []
    if not path_to_kill_scores_file.exists():
        return mutation_testing_results
    lines = path_to_kill_scores_file.read_text(encoding="utf-8").splitlines()
    subject_file_name = _get_file_name(lines[0])
    for raw_line in lines:
        try:
            kill_score_data = ast.literal_eval(raw_line)
            kill_score_data["file_name"] = subject_file_name
            mutation_testing_results.append(
                MutationTestingResultForFunction(**kill_score_data)
            )
        except Exception:
            continue
    return mutation_testing_results


def _get_file_name(file_path_log_line: str) -> str:
    # Split the string from the right at the " - Processing " marker.
    file_path_str = file_path_log_line.rsplit(" - Processing ", 1)[-1]
    return Path(file_path_str).name


def get_table_rows(
    file_to_treatment_scores: dict[str, dict[str, SubjectKillScore]],
) -> list[str]:
    """Return all the (data) rows of the mutation kill-scores table.

    Args:
        file_to_treatment_scores (dict[str, dict[str, SubjectKillScore]]): Map from subject
            file name to per-treatment aggregated kill scores.

    Returns:
        list[str]: The data rows of the mutation kill-scores table.
    """
    lines = []
    for file_name in sorted(file_to_treatment_scores):
        scores_by_treatment = file_to_treatment_scores[file_name]
        num_mutants = mutants_column_value(scores_by_treatment)
        kill_scores = [
            scores_by_treatment[treatment].kill_score
            if treatment in scores_by_treatment
            else None
            for treatment in TREATMENTS
        ]
        lines.append(get_row(f"\\<{file_name}>", num_mutants, kill_scores))
    return lines


def mutants_column_value(
    scores_by_treatment: dict[str, SubjectKillScore],
) -> int | None:
    """Return the value of the `Mutants` column for a subject (Full treatment's total)."""
    score = scores_by_treatment.get(MUTANTS_COLUMN_TREATMENT)
    if score is None or score.num_mutants == 0:
        return None
    return score.num_mutants


def get_row(
    file_name: str,
    num_mutants: int | None,
    kill_scores_per_treatment: list[float | None],
) -> str:
    """Return one row of the mutation kill-scores table.

    Args:
        file_name (str): The subject file name (or the Total label).
        num_mutants (int | None): The value of the `Mutants` column, or None if unknown.
        kill_scores_per_treatment (list[float | None]): The kill score per treatment, or None
            for a treatment with missing data.

    Returns:
        str: One row of the mutation kill-scores table.
    """
    # Bold on the displayed (rounded) value so cells that print the same score
    # (e.g. several treatments rounding to the same two-decimal max) are all bolded.
    rounded_scores = [
        round(score, 2) for score in kill_scores_per_treatment if score is not None
    ]
    max_kill_score = max(rounded_scores) if rounded_scores else None
    cells = [str(num_mutants) if num_mutants is not None else MISSING_CELL]
    for kill_score in kill_scores_per_treatment:
        if kill_score is None:
            cells.append(MISSING_CELL)
            continue
        cell = f"{kill_score:.2f}"
        if round(kill_score, 2) == max_kill_score:
            cell = f"\\textbf{{{cell}}}"
        cells.append(cell)
    return f"{file_name} & {' & '.join(cells)} \\\\"


if __name__ == "__main__":
    main()
